export const DESIGN = {
    // Pair Designs
    AMBULANCOPTERYNC: 'AMBULANCOPTERYNC',
    HIGH_SPEED_MEDIC: 'HIGH_SPEED_MEDIC',
    EXPLOSIVE_HEALING: 'EXPLOSIVE_HEALING',
    LOTTERY_AMBULANCE: 'LOTTERY_AMBULANCE',
    TRAINWRECK_RESCUE: 'TRAINWRECK_RESCUE',
    SKY_WARRIORS: 'SKY_WARRIORS',
    ARMADO_HELICOPTER: 'ARMADO_HELICOPTER',
    SPINNING_ROTOR: 'SPINNING_ROTOR',
    SKYLINE_CARAVAN: 'SKYLINE_CARAVAN',
    JET_MISSILE_BARRAGE: 'JET_MISSILE_BARRAGE',
    LUCKY_ACE: 'LUCKY_ACE',
    SONIC_RAIL: 'SONIC_RAIL',
    LOTTERY_STRIKE: 'LOTTERY_STRIKE',
    RUNAWAY_EXPLOSION: 'RUNAWAY_EXPLOSION',
    FORTUNE_TRAIN: 'FORTUNE_TRAIN',
    // Alien Designs
    ALIEN_AMBULANCE: 'ALIEN_AMBULANCE',
    ALIEN_HELICOPTER: 'ALIEN_HELICOPTER',
    ALIEN_JET: 'ALIEN_JET',
    ALIEN_MISSILE: 'ALIEN_MISSILE',
    ALIEN_SLOT_MACHINE: 'ALIEN_SLOT_MACHINE',
    ALIEN_TRAIN: 'ALIEN_TRAIN',
} as const;

export type DESIGN = typeof DESIGN[keyof typeof DESIGN];